import tqdm
import numpy as np
import torch
import pickle
import os
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation, writers
from matplotlib.collections import LineCollection
import matplotlib as mpl
# plt.rcParams.update({'font.size': 16})

plt.rc('text', usetex=True)
plt.rc('font', size=16)  # use 13 for squared double columns figures
mpl.rc('xtick', labelsize=16)
mpl.rc('ytick', labelsize=16)
mpl.rc('figure', max_open_warning=0)
mpl.rcParams['axes.linewidth'] = 0.5
mpl.rcParams['axes.unicode_minus'] = False
mpl.rcParams['text.latex.preamble'] = r'\usepackage{amsmath}' #for \text command
# mpl.rcParams['font.family'] = 'cm'' #for \text command
# plt.style.use('ggplot')

class Streamlines(object):
    """
    Copyright (c) 2011 Raymond Speth.

    Permission is hereby granted, free of charge, to any person obtaining a
    copy of this software and associated documentation files (the "Software"),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in
    all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.

    See: http://web.mit.edu/speth/Public/streamlines.py
    """

    def __init__(self, X, Y, U, V, res=0.125,
                 spacing=2, maxLen=2500, detectLoops=False):
        """
        Compute a set of streamlines covering the given velocity field.

        X and Y - 1D or 2D (e.g. generated by np.meshgrid) arrays of the
                  grid points. The mesh spacing is assumed to be uniform
                  in each dimension.
        U and V - 2D arrays of the velocity field.
        res - Sets the distance between successive points in each
              streamline (same units as X and Y)
        spacing - Sets the minimum density of streamlines, in grid points.
        maxLen - The maximum length of an individual streamline segment.
        detectLoops - Determines whether an attempt is made to stop extending
                      a given streamline before reaching maxLen points if
                      it forms a closed loop or reaches a velocity node.

        Plots are generated with the 'plot' or 'plotArrows' methods.
        """

        self.spacing = spacing
        self.detectLoops = detectLoops
        self.maxLen = maxLen
        self.res = res

        xa = np.asanyarray(X)
        ya = np.asanyarray(Y)
        self.x = xa if xa.ndim == 1 else xa[0]
        self.y = ya if ya.ndim == 1 else ya[:,0]
        self.u = U
        self.v = V
        self.dx = (self.x[-1]-self.x[0])/(self.x.size-1) # assume a regular grid
        self.dy = (self.y[-1]-self.y[0])/(self.y.size-1) # assume a regular grid
        self.dr = self.res * np.sqrt(self.dx * self.dy)

        # marker for which regions have contours
        self.used = np.zeros(self.u.shape, dtype=bool)
        self.used[0] = True
        self.used[-1] = True
        self.used[:,0] = True
        self.used[:,-1] = True

        # Don't try to compute streamlines in regions where there is no velocity data
        for i in range(self.x.size):
            for j in range(self.y.size):
                if self.u[j,i] == 0.0 and self.v[j,i] == 0.0:
                    self.used[j,i] = True

        # Make the streamlines
        self.streamlines = []
        while not self.used.all():
            nz = np.transpose(np.logical_not(self.used).nonzero())
            # Make a streamline starting at the first unrepresented grid point
            self.streamlines.append(self._makeStreamline(self.x[nz[0][1]],
                                                         self.y[nz[0][0]]))


    def _interp(self, x, y):
        """ Compute the velocity at point (x,y) """
        i = (x-self.x[0])/self.dx
        ai = i % 1

        j = (y-self.y[0])/self.dy
        aj = j % 1

        i, j = int(i), int(j)
        
        # Bilinear interpolation
        u = (self.u[j,i]*(1-ai)*(1-aj) +
             self.u[j,i+1]*ai*(1-aj) +
             self.u[j+1,i]*(1-ai)*aj +
             self.u[j+1,i+1]*ai*aj)

        v = (self.v[j,i]*(1-ai)*(1-aj) +
             self.v[j,i+1]*ai*(1-aj) +
             self.v[j+1,i]*(1-ai)*aj +
             self.v[j+1,i+1]*ai*aj)

        self.used[j:j+self.spacing,i:i+self.spacing] = True

        return u,v

    def _makeStreamline(self, x0, y0):
        """
        Compute a streamline extending in both directions from the given point.
        """

        sx, sy = self._makeHalfStreamline(x0, y0, 1) # forwards
        rx, ry = self._makeHalfStreamline(x0, y0, -1) # backwards

        rx.reverse()
        ry.reverse()

        return rx+[x0]+sx, ry+[y0]+sy

    def _makeHalfStreamline(self, x0, y0, sign):
        """
        Compute a streamline extending in one direction from the given point.
        """

        xmin = self.x[0]
        xmax = self.x[-1]
        ymin = self.y[0]
        ymax = self.y[-1]

        sx = []
        sy = []

        x = x0
        y = y0
        i = 0
        while xmin < x < xmax and ymin < y < ymax:
            u, v = self._interp(x, y)
            theta = np.arctan2(v,u)

            x += sign * self.dr * np.cos(theta)
            y += sign * self.dr * np.sin(theta)
            sx.append(x)
            sy.append(y)

            i += 1

            if self.detectLoops and i % 10 == 0 and self._detectLoop(sx, sy):
                break

            if i > self.maxLen / 2:
                break

        return sx, sy

    def _detectLoop(self, xVals, yVals):
        """ Detect closed loops and nodes in a streamline. """
        x = xVals[-1]
        y = yVals[-1]
        D = np.array([np.hypot(x-xj, y-yj)
                      for xj,yj in zip(xVals[:-1],yVals[:-1])])
        return (D < 0.9 * self.dr).any()
    

#! Importing libraries
from scipy.integrate import odeint
from scipy.optimize import fsolve, minimize, root
from matplotlib.lines import Line2D
import os
import pickle
# plt.style.use('ggplot')

# delete if not needed
######
from pathlib import Path
import sys
path_root = Path(__file__).parents[2]
sys.path.append(str(path_root))

import os
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"
######

import args
from src.utils import get_args, set_seed, set_torch_dtype  #, set_torch_multiprocessing
# import src.config


#! Set parameters
# Get args
args = get_args(args)

# Set float precision
set_torch_dtype(args.ftype)

# Set seed for reproducibility
set_seed(args.seed)


#! Solving ODE
def blasius_eq(f,z):
    return f[1], f[2], -f[0]*f[2]/2

def find_c0(f2_0):
    f = odeint(blasius_eq, (0,0,f2_0), [0, 10])
    return 1.-f[-1, 1]

f0_0, f1_0 = 0, 0
f2_0 = fsolve(find_c0, .5)

def solve_pointwise(z, density=250):
    initial = f0_0, f1_0, f2_0
    z_span = np.linspace(0,z,int(z*density))
    f, f_z, f_zz = odeint(blasius_eq, initial, z_span).T
    return f, f_z, f_zz, z_span

def quantities(x, y, visc, U_inf):
    pi1 = np.sqrt(U_inf * x / visc) # Re_x = x/delta
    pi2 = y * np.sqrt(U_inf / (visc * x)) # eta = y/delta

    f, f_z,*_ = solve_pointwise(pi2, density=250)
    f, f_z = f[-1] if len(f) else 0, f_z[-1] if len(f_z) else 0
    u = U_inf * f_z     # u = U_inf * f'
    v = U_inf/(2*pi1)*(pi2 * f_z - f)   # v = 1/(2*pi1) * (pi2 * f' - f)

    psi = U_inf * y * f / pi2 if y!=0 else 0


    return u, v, psi

# make quantities a vectorized function
quantities = np.vectorize(quantities, otypes=[args.ftype, args.ftype, args.ftype])

def bl_thickness(x, visc, U_inf):
    return 5*np.sqrt(x*visc/U_inf)

def main():
    N = int(2.5e2)
    
    visc = 1/5e4
    U_inf = 1

    # x0 = .8
    # x_ = np.repeat(x0,N)
    # y_ = np.linspace(0,bl_t   hickness(x0,visc,U_inf),N)
    # U, V, psi = quantities(x_, y_, visc, U_inf)
    # plt.plot(V,y_*np.sqrt(U_inf/(visc*x_)))
    # plt.show()

    x_ = np.linspace(1e-5,1,N)
    y_ = np.linspace(0,5e-2,N)
    X,Y = np.meshgrid(x_,y_)

    U, V, psi = quantities(X, Y, visc, U_inf)
    U,V = -U,-V

    speed = np.sqrt(U**2 + V**2)

    bl = bl_thickness(x_, visc, U_inf)

    fig, ax = plt.subplots(figsize=(10,10))
    # fig, ax = plt.subplots(figsize=(16,9))
    
    levels = np.linspace(0,1,60)**2

    im = ax.imshow(speed, extent=[1e-5,1,0,5e-2], origin='lower', cmap='viridis', alpha=.85)
    plt.colorbar(im, ax=ax, orientation='vertical', label=r'$\text{velocity norm}$', fraction=0.046, pad=0.04)
    ax.contour(X,Y,psi,levels=30,linewidths=.9, colors='whitesmoke')
    ax.plot(x_, bl, color='firebrick', linestyle='--', linewidth=1.5, label=r'$\delta_{99}$')
    # ax.contour(X,Y,psi,levels=levels,linewidths=.9, colors='whitesmoke')
    ax.set_aspect(20)
    ax.set_xlabel(r'$x$')
    ax.set_ylabel(r'$y$')
    ax.legend()
    # plt.tight_layout()
    fname = 'imgs/bank/testcases/flatplate_velocity_field_stream.png'
    # plt.savefig(fname, bbox_inches='tight', dpi=256)
    plt.show()


    DO_GIF = False
    if DO_GIF:


        fig = plt.figure(figsize=(10,10))
        # fig = plt.figure(figsize=(19.8,9))
        ax = plt.subplot(1, 1, 1, aspect=1)



        lengths = []
        colors = []
        lines = []

        s = Streamlines(X, Y, U, V, res=0.1, spacing=3, maxLen=1500, detectLoops=False)

        
        # print(len(s.streamlines[100]))
        # print(s.streamlines[100])
        # x,y = s.streamlines[100]
        # plt.plot(x,y)
        # plt.gca().set_aspect(20)
        # plt.show()
        for streamline in s.streamlines:
            x, y = streamline
            points = np.array([x, y]).T.reshape(-1, 1, 2)
            segments = np.concatenate([points[:-1], points[1:]], axis=1)
            n = len(segments)
            
            D = np.sqrt(((points[1:] - points[:-1])**2).sum(axis=-1))
            L = D.cumsum().reshape(n,1) + np.random.normal()
            C = np.zeros((n,3))
            C[:] = (L*1.5) % 1

            #linewidths = np.zeros(n)
            #linewidths[:] = 1.5 - ((L.reshape(n)*1.5) % 1)

            # line = LineCollection(segments, color=colors, linewidth=linewidths)
            line = LineCollection(segments, color=C, linewidth=.5)
            lengths.append(L)
            colors.append(C)
            lines.append(line)
            
            ax.add_collection(line)

        def update(frame_no):
            for i in range(len(lines)):
                lengths[i] += 0.05
                # for j in range(len(lengths[i])):
                #     pt = lines[i].get_segments()[j][0]
                #     sp = np.linalg.norm(s._interp(pt[0], pt[1]))
                #     # print(sp)
                #     lengths[i][j] += 0.05*sp
                colors[i][:] = (lengths[i]*1.5) % 1
                lines[i].set_color(colors[i])
            pbar.update()

        scale = 2.5
        ax.set_xlim(1e-5,1), ax.set_xticks([])
        ax.set_ylim(0,5e-2), ax.set_yticks([])
        ax.set_aspect(20)
        ax.set_xlabel(r'$x$', fontsize=25)
        ax.set_ylabel(r'$y$', fontsize=25)

        # fill between y=0 and bl thickness
        ax.fill_between(x_, 0, bl, color='firebrick', alpha=.2)

        plt.tight_layout()

        y = np.linspace(0,5e-2,25)
        x = np.full_like(y, 1e-5) 
        # u = -U[::2,0]
        # v = -V[::2,0]
        u = U_inf*3
        v = np.zeros_like(u)
        ax.quiver(x,y,u,v, color='firebrick', scale=scale, width=3e-3, scale_units='inches', alpha=.7, zorder=10)

        n = 27
        # animation = FuncAnimation(fig, update, interval=10)
        animation = FuncAnimation(fig, update, frames=n, interval=20)
        pbar = tqdm.tqdm(total=n)
        # animation.save('wind.mp4', writer='ffmpeg', fps=60)
        fname = 'imgs/bank/testcases/flat_plate_streamlines_ani_test.gif'
        animation.save(fname, writer='imagemagick', fps=20)
        pbar.close()
        plt.show()

if __name__=='__main__':
    main()